name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
           docker build -t next-app .
           docker tag next-app:latest haideralibjs/next-app:latest
           
    - name: Docker login
    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
     
    - name: Docker Push
      run: |
           docker push haideralibjs/next-app:latest

        

